[phases.setup]
nixPkgs = ["php82", "php82Packages.composer"]

[phases.build]
cmds = [
  "cd backend && composer install --no-dev --optimize-autoloader"
]

[start]
cmd = "cd backend && php artisan serve --host=0.0.0.0 --port=$PORT"
